# -*- coding: utf-8 -*-
"""Capstone Project (9 Disease classes )

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyRf8aGCfQJD9BaSzFBwvrARy9_-Op2J
"""

import kagglehub
import os
import shutil

# Define the target directory in /content
target_dataset_path = "/content/NIH_Chest_Xrays_Dataset"

print("Downloading NIH Chest X-rays dataset...")

# Download latest version of the dataset
# This downloads to the KaggleHub cache directory
downloaded_path = kagglehub.dataset_download("nih-chest-xrays/data")

print(f"Dataset initially downloaded to: {downloaded_path}")

# Ensure the target directory for moving exists
if os.path.exists(target_dataset_path):
    print(f"Removing existing directory: {target_dataset_path}")
    shutil.rmtree(target_dataset_path)

# Move the downloaded dataset to the target path in /content
# shutil.move handles moving files/directories across different file systems
print(f"Moving dataset from {downloaded_path} to {target_dataset_path}...")
shutil.move(downloaded_path, target_dataset_path)

print(f"NIH Chest X-rays dataset is now available at: {target_dataset_path}")

# Update the 'path' variable to reflect the final location
path = target_dataset_path

import os
import shutil
from pathlib import Path
from PIL import Image, ImageOps
import torchvision.transforms as transforms

# Assuming target_dataset_path is available from previous cell execution
# target_dataset_path = "/content/NIH_Chest_Xrays_Dataset"

def preprocess_dataset_and_save(
    input_root: Path,
    output_root: Path,
    image_size: tuple = (224, 224),
    equalize: bool = False
):
    """
    Processes images from input_root, applies resizing and optional equalization,
    and saves them as new image files to output_root, maintaining the directory structure.
    """
    output_root.mkdir(parents=True, exist_ok=True)
    processed_count = 0
    skipped_count = 0

    # Define the transforms that result in a PIL Image
    pil_resize_transform = transforms.Resize(image_size)

    for dirpath, dirnames, filenames in os.walk(input_root):
        # Construct relative path from input_root to current dirpath
        try:
            relative_path = Path(dirpath).relative_to(input_root)
        except ValueError:
            # If dirpath is not a child of input_root (e.g., if input_root is a file),
            # handle it by setting relative_path to an empty path.
            relative_path = Path('.')

        target_dir = output_root / relative_path
        target_dir.mkdir(parents=True, exist_ok=True)

        for filename in filenames:
            # Process only common image file types
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif')):
                try:
                    img_path = Path(dirpath) / filename
                    # Open image and convert to RGB to handle various input formats consistently
                    img = Image.open(img_path).convert('RGB')

                    # Apply resizing transform
                    img = pil_resize_transform(img)

                    # Apply histogram equalization if requested
                    if equalize:
                        img = ImageOps.equalize(img)

                    target_img_path = target_dir / filename
                    img.save(target_img_path) # Save the processed PIL image
                    processed_count += 1
                except Exception as e:
                    print(f"Skipping {img_path} due to error: {e}")
                    skipped_count += 1
            else:
                skipped_count += 1
    return processed_count, skipped_count

# --- Apply preprocessing to the NIH Chest X-rays dataset ---
# The variable 'target_dataset_path' should be available from the execution of cell o2k0jrq2-6jZ

if 'target_dataset_path' in globals():
    nih_input_path = Path(target_dataset_path)
    nih_output_path = Path("/content/NIH_Chest_Xrays_Preprocessed")

    print(f"\nApplying preprocessing to NIH Chest X-rays dataset and saving to: {nih_output_path}")

    IMG_SIZE = 224 # Set image size, consistent with common model input requirements

    # Clean up previous data from target directory to ensure a clean run
    if nih_output_path.exists():
        print(f"Removing existing directory: {nih_output_path}")
        shutil.rmtree(nih_output_path)

    processed_nih, skipped_nih = preprocess_dataset_and_save(
        input_root=nih_input_path,
        output_root=nih_output_path,
        image_size=(IMG_SIZE, IMG_SIZE),
        equalize=True # Apply equalization
    )

    print(f"NIH Image preprocessing complete. Processed: {processed_nih}, Skipped: {skipped_nih}")
    print(f"Preprocessed NIH Chest X-rays images saved to: {nih_output_path}")

    # Make the path to the preprocessed NIH dataset available for subsequent cells
    path_nih_preprocessed = nih_output_path
else:
    print("Error: 'target_dataset_path' for NIH dataset not found. Please ensure the dataset download cell (o2k0jrq2-6jZ) is executed.")

import pandas as pd
import numpy as np
import os
import shutil
from pathlib import Path
from sklearn.model_selection import train_test_split

# --- Imports and function from 1ZlcAoHP_ehA to ensure preprocessing if not already done ---
from PIL import Image, ImageOps
import torchvision.transforms as transforms

def preprocess_dataset_and_save(
    input_root: Path,
    output_root: Path,
    image_size: tuple = (224, 224),
    equalize: bool = False
):
    """
    Processes images from input_root, applies resizing and optional equalization,
    and saves them as new image files to output_root, maintaining the directory structure.
    """
    output_root.mkdir(parents=True, exist_ok=True)
    processed_count = 0
    skipped_count = 0

    pil_resize_transform = transforms.Resize(image_size)

    for dirpath, dirnames, filenames in os.walk(input_root):
        try:
            relative_path = Path(dirpath).relative_to(input_root)
        except ValueError:
            relative_path = Path('.')

        target_dir = output_root / relative_path
        target_dir.mkdir(parents=True, exist_ok=True)

        for filename in filenames:
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.tiff', '.bmp', '.gif')):
                try:
                    img_path = Path(dirpath) / filename
                    img = Image.open(img_path).convert('RGB')
                    img = pil_resize_transform(img)
                    if equalize:
                        img = ImageOps.equalize(img)

                    target_img_path = target_dir / filename
                    img.save(target_img_path)
                    processed_count += 1
                except Exception as e:
                    print(f"Skipping {img_path} due to error: {e}")
                    skipped_count += 1
            else:
                skipped_count += 1
    return processed_count, skipped_count
# --- End of preprocessing function from 1ZlcAoHP_ehA ---


# --- 1. Define Paths and Ratios ---
# Path to the preprocessed NIH dataset (output of cell 1ZlcAoHP_ehA)
preprocessed_nih_path = Path("/content/NIH_Chest_Xrays_Preprocessed")
# Path to the original NIH dataset (output of cell o2k0jrq2-6jZ) for CSV label extraction
original_nih_path = Path("/content/NIH_Chest_Xrays_Dataset")

# Ensure preprocessing is done if the directory doesn't exist
# This ensures that the dataset splitting can proceed even if 1ZlcAoHP_ehA was not run.
if not preprocessed_nih_path.exists():
    print(f"Preprocessing directory {preprocessed_nih_path} not found. Running preprocessing now...")
    # These variables are expected to be available from previous cells/kernel state
    # 'target_dataset_path' is '/content/NIH_Chest_Xrays_Dataset' from o2k0jrq2-6jZ
    # 'IMG_SIZE' is 224 from kernel state
    # 'equalize=True' is the default from 1ZlcAoHP_ehA

    # Check if target_dataset_path is available from the kernel state
    if 'target_dataset_path' not in globals():
        raise RuntimeError("Error: 'target_dataset_path' not found. Please ensure the dataset download cell (o2k0jrq2-6jZ) has been executed.")
    if 'IMG_SIZE' not in globals():
        # If IMG_SIZE is not set, use a default value for preprocessing
        print("Warning: 'IMG_SIZE' not found in kernel state. Using default 224 for preprocessing.")
        current_img_size = 224
    else:
        current_img_size = IMG_SIZE

    processed_nih, skipped_nih = preprocess_dataset_and_save(
        input_root=Path(target_dataset_path), # Using 'target_dataset_path' from kernel state
        output_root=preprocessed_nih_path,
        image_size=(current_img_size, current_img_size),
        equalize=True # Replicating 1ZlcAoHP_ehA's equalization
    )
    print(f"Preprocessing completed. Processed: {processed_nih}, Skipped: {skipped_nih}")

# Output directory for the split dataset
split_output_base_path = Path("/content/datasplitting") # Modified to 'datasplitting'

TRAIN_RATIO = 0.70
VAL_RATIO = 0.15
TEST_RATIO = 0.15

# Ensure the preprocessed data path exists (after attempting to create it)
if not preprocessed_nih_path.exists():
    raise FileNotFoundError(f"Preprocessed NIH dataset not found at {preprocessed_nih_path} even after attempting to create it.")
if not original_nih_path.exists():
    raise FileNotFoundError(f"Original NIH dataset not found at {original_nih_path}. "
                            "Please ensure the dataset download cell (o2k0jrq2-6jZ) has been executed.")

# Clean up previous splits if they exist
if split_output_base_path.exists():
    print(f"Removing existing split directory: {split_output_base_path}")
    shutil.rmtree(split_output_base_path)
split_output_base_path.mkdir(parents=True, exist_ok=True)

# --- 2. Load Original Labels ---
# The NIH dataset comes with a CSV file containing image labels
labels_csv_path = original_nih_path / "Data_Entry_2017.csv"
if not labels_csv_path.exists():
    # Try alternative common path for the CSV within the dataset structure
    labels_csv_path = original_nih_path / "NIH-Chest-X-rays" / "Data_Entry_2017.csv"
    if not labels_csv_path.exists():
        raise FileNotFoundError(f"Labels CSV not found at expected paths: {original_nih_path / 'Data_Entry_2017.csv'} or {labels_csv_path}")

df_labels = pd.read_csv(labels_csv_path)

# --- 3. Define Label Mapping Strategy ---
# User-defined diseases + 1 Normal class
user_classes = {
    'NORMAL': ['No Finding'],
    'LUNG OPACITY': ['Atelectasis'], # Mapped Atelectasis
    'COVID': [], # No direct NIH finding
    'PNEUMONIA': ['Viral Pneumonia', 'Bacterial Pneumonia', 'Infiltration', 'Consolidation'],
    'PLEURAL EFFUSION': ['Effusion', 'Pleural_Thickening'],
    'LUNG CANCER': ['Mass', 'Nodule'],
    'PNEUMOTHORAX': ['Pneumothorax'],
    'EMPHYSEMA': ['Emphysema'],
    'PULMONARY FIBROSIS': ['Fibrosis'],
    'SARS': [], # No direct NIH finding
    'MARS': [], # Adding MARS back, no direct NIH finding
    'TUBERCULOSIS': [], # No direct NIH finding
    'LUNG INFECTION': ['Edema'] # Mapped Edema
}

# Create a reverse mapping for quick lookup
reverse_mapping = {}
for user_class, nih_findings in user_classes.items():
    for finding in nih_findings:
        # Prioritize single specific NIH finding to user class mapping
        # If multiple NIH findings map to the same user class, this will handle it.
        reverse_mapping[finding] = user_class

# Function to get the primary standardized label
def get_primary_standard_label(finding_labels_str):
    labels = finding_labels_str.split('|')

    # Prioritize 'No Finding' for 'NORMAL' class
    if 'No Finding' in labels:
        return 'NORMAL'

    # Iterate through labels and map to a user-defined disease
    for label in labels:
        if label in reverse_mapping:
            return reverse_mapping[label]

    # If no specific disease from the user's list is found for disease-labeled images,
    # or if the label is one of the findings not directly listed by user (e.g., Cardiomegaly, Hernia)
    # return a special tag for unmapped/excluded. We will filter these out later.
    return '__UNMAPPED__'

df_labels['standardized_label'] = df_labels['Finding Labels'].apply(get_primary_standard_label)

# Filter out images that could not be mapped to the specified classes
df_filtered = df_labels[df_labels['standardized_label'] != '__UNMAPPED__'].copy()

print(f"Original images: {len(df_labels)}")
print(f"Images mapped to one of the {len(user_classes)} specified classes: {len(df_filtered)}")
print("Distribution of standardized labels:")
print(df_filtered['standardized_label'].value_counts())

# --- 4. Collect Preprocessed Image Paths and Merge with Labels ---
image_data = []
# Assuming preprocessed images are in a structure like /content/NIH_Chest_Xrays_Preprocessed/images/image_name.png
# or if the original structure was flattened, directly under /content/NIH_Chest_Xrays_Preprocessed/

# Need to find the actual directory where preprocessed images are stored
# From cell 1ZlcAoHP_ehA, output is Path("/content/NIH_Chest_Xrays_Preprocessed")
# and it preserves the original relative path, so it should be preprocessed_nih_path / 'images' / ...

# Let's verify the actual image folder, it is usually `images` folder within the `nih_output_path`
# Example: /content/NIH_Chest_Xrays_Preprocessed/images_001/images/00000001_000.png
# or /content/NIH_Chest_Xrays_Preprocessed/images/00000001_000.png

# Try to find the root folder for images in the preprocessed path
image_root_in_preprocessed = None
for root, dirs, files in os.walk(preprocessed_nih_path):
    if any(f.lower().endswith(('.png', '.jpg', '.jpeg')) for f in files):
        image_root_in_preprocessed = Path(root)
        break

if image_root_in_preprocessed is None:
    raise FileNotFoundError(f"Could not find image files within {preprocessed_nih_path}. "
                            "Check the structure of the preprocessed dataset.")

# Adjust preprocessed_nih_path to point to the actual image directory
preprocessed_images_base_path = image_root_in_preprocessed


for image_path in preprocessed_images_base_path.rglob('*.png'): # Assuming .png as preprocessed output
    image_index = image_path.name # Filename is Image Index
    image_data.append({'Image Index': image_index, 'processed_image_path': str(image_path)})

df_processed_images = pd.DataFrame(image_data)

# Merge labels with processed image paths
df_final = pd.merge(df_processed_images, df_filtered, on='Image Index', how='inner')

print(f"Total images after filtering and merging: {len(df_final)}")
print("Final distribution of classes after mapping and filtering:")
print(df_final['standardized_label'].value_counts())

# --- 5. Perform Stratified Train-Validation-Test Split ---
# First split: Train vs (Validation + Test)
X = df_final['processed_image_path']
y = df_final['standardized_label']

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=(VAL_RATIO + TEST_RATIO), stratify=y, random_state=42)

# Second split: Validation vs Test
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=(TEST_RATIO / (VAL_RATIO + TEST_RATIO)), stratify=y_temp, random_state=42)

# Create DataFrames for each split
df_train = pd.DataFrame({'processed_image_path': X_train, 'standardized_label': y_train})
df_val = pd.DataFrame({'processed_image_path': X_val, 'standardized_label': y_val})
df_test = pd.DataFrame({'processed_image_path': X_test, 'standardized_label': y_test})

print(f"\nTrain set size: {len(df_train)}")
print(f"Validation set size: {len(df_val)}")
print(f"Test set size: {len(df_test)}")

# --- 6. Create Directory Structure and Copy Images ---
def copy_images_to_splits(df_split, split_name):
    split_dir = split_output_base_path / split_name
    print(f"Creating {split_name} directories and copying images...")
    for idx, row in df_split.iterrows():
        label_dir = split_dir / row['standardized_label']
        label_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy(row['processed_image_path'], label_dir / Path(row['processed_image_path']).name)

copy_images_to_splits(df_train, 'train')
copy_images_to_splits(df_val, 'validation')
copy_images_to_splits(df_test, 'test')

print(f"\nDataset splitting complete. Data saved to: {split_output_base_path}")

# Print final counts per class in each split for verification
print("\nClass distribution in Training set:")
print(df_train['standardized_label'].value_counts())
print("\nClass distribution in Validation set:")
print(df_val['standardized_label'].value_counts())
print("\nClass distribution in Test set:")
print(df_test['standardized_label'].value_counts())

"""### Model Training Setup

This cell sets up and executes the training process for a `FastViT-T8` model. It leverages the preprocessed and split NIH Chest X-rays dataset generated in the previous steps.

**Key configurations:**

-   **Model:** `FastViT-T8` (pre-trained on ImageNet)
-   **Optimizer:** `AdamW`
-   **Learning Rate (LR):** `3e-4`
-   **Batch Size:** `8`
-   **Epochs:** `10` (can be adjusted up to 15 or more)
-   **Image Size:** `224x224` (compatible with most pre-trained models)
-   **Device:** Automatically selects `CUDA` if a GPU is available, otherwise falls back to `CPU`.

**Dependencies:**

This cell relies on the successful execution of:
-   **Cell `o2k0jrq2-6jZ`:** For downloading and moving the original NIH Chest X-rays dataset.
-   **Cell `1ZlcAoHP_ehA`:** For preprocessing the NIH Chest X-rays dataset (resizing and equalization).
-   **Cell `41c5157c`:** For splitting the preprocessed NIH dataset into `train`, `validation`, and `test` directories with their respective class labels.

The training process includes data augmentation, a validation step per epoch, and saves the best model based on validation loss. Finally, it evaluates the best model on the test set.
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from timm import create_model
import os

# --- Configuration ---
MODEL_NAME = "fastvit_t8"
OPTIMIZER = "AdamW"
LR = 3e-4
BATCH_SIZE = 8
EPOCHS = 10 # User specified 10-15 epochs, starting with 10
IMG_SIZE = 224 # User specified 224 (or 160 for speed)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Using device: {DEVICE}")

# --- Paths (assuming previous cells have been executed) ---
# The split dataset path from cell 41c5157c
split_dataset_base_path = "/content/datasplitting" # Corrected path to match cell 41c5157c output

train_dir = os.path.join(split_dataset_base_path, 'train')
val_dir = os.path.join(split_dataset_base_path, 'validation')
test_dir = os.path.join(split_dataset_base_path, 'test')

# Check if dataset directories exist
if not os.path.exists(train_dir):
    raise FileNotFoundError(f"Training directory not found: {train_dir}. Please ensure dataset splitting cell (41c5157c) has been executed.")
if not os.path.exists(val_dir):
    raise FileNotFoundError(f"Validation directory not found: {val_dir}. Please ensure dataset splitting cell (41c5157c) has been executed.")
if not os.path.exists(test_dir):
    raise FileNotFoundError(f"Test directory not found: {test_dir}. Please ensure dataset splitting cell (41c5157c) has been executed.")


# --- Data Transforms ---
# Basic transforms for training (with augmentation) and ImageNet normalization
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1, hue=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # ImageNet normalization
])

# Validation and test transforms (no augmentation) with ImageNet normalization
val_test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# --- Datasets ---
train_dataset = datasets.ImageFolder(train_dir, transform=train_transform)
val_dataset = datasets.ImageFolder(val_dir, transform=val_test_transform)
test_dataset = datasets.ImageFolder(test_dir, transform=val_test_transform)

# --- Data Loaders ---
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2) # num_workers for faster loading
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

print(f"Number of classes: {len(train_dataset.classes)}")
print(f"Train dataset size: {len(train_dataset)}")
print(f"Validation dataset size: {len(val_dataset)}")
print(f"Test dataset size: {len(test_dataset)}")

# --- Model ---
# Ensure timm library is installed: !pip install timm
try:
    model = create_model(MODEL_NAME, pretrained=True, num_classes=len(train_dataset.classes))
    model = model.to(DEVICE)
    print(f"Model '{MODEL_NAME}' loaded successfully with {len(train_dataset.classes)} output classes.")
except Exception as e:
    print(f"Error loading model: {e}. Please ensure 'timm' is installed and model name '{MODEL_NAME}' is correct.")
    raise # Re-raise the exception to stop execution if model fails to load

# --- Loss Function and Optimizer ---
criterion = nn.CrossEntropyLoss()
if OPTIMIZER == "AdamW":
    optimizer = optim.AdamW(model.parameters(), lr=LR)
else:
    # Default to Adam if other optimizers are not explicitly handled
    optimizer = optim.Adam(model.parameters(), lr=LR)
print(f"Optimizer: {OPTIMIZER} with LR={LR}")

# --- Training Loop ---
print("Starting training...")
best_val_loss = float('inf')

# Lists to store metrics
train_losses = []
train_accuracies = []
val_losses = []
val_accuracies = []

for epoch in range(EPOCHS):
    model.train()
    running_loss = 0.0
    correct_train = 0
    total_train = 0
    for i, (inputs, labels) in enumerate(train_loader):
        inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * inputs.size(0)
        _, predicted_train = torch.max(outputs.data, 1)
        total_train += labels.size(0)
        correct_train += (predicted_train == labels).sum().item()

    epoch_loss = running_loss / len(train_dataset)
    epoch_accuracy = 100 * correct_train / total_train
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_accuracy)
    print(f"Epoch {epoch+1}/{EPOCHS}, Train Loss: {epoch_loss:.4f}, Train Accuracy: {epoch_accuracy:.2f}%")

    # --- Validation ---
    model.eval() # Set model to evaluation mode
    val_running_loss = 0.0
    correct_val = 0
    total_val = 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            val_running_loss += loss.item() * inputs.size(0)
            _, predicted_val = torch.max(outputs.data, 1)
            total_val += labels.size(0)
            correct_val += (predicted_val == labels).sum().item()

    val_loss = val_running_loss / len(val_dataset)
    val_accuracy = 100 * correct_val / total_val
    val_losses.append(val_loss)
    val_accuracies.append(val_accuracy)
    print(f"Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy:.2f}%")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), 'best_model.pth') # Save the model state_dict
        print("Saved best model based on validation loss!")

print("Training complete.")

# --- Evaluate on Test Set ---
# Load the best model weights before evaluating on the test set
model.load_state_dict(torch.load('best_model.pth'))
model.eval() # Set model to evaluation mode
test_loss = 0.0
correct_test = 0
total_test = 0

# Variables to store all predictions and labels for confusion matrix and classification report
all_labels = []
all_predictions = []

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(DEVICE), labels.to(DEVICE)
        outputs = model(inputs)
        loss = criterion(outputs, labels)
        test_loss += loss.item() * inputs.size(0)
        _, predicted_test = torch.max(outputs.data, 1)
        total_test += labels.size(0)
        correct_test += (predicted_test == labels).sum().item()

        all_labels.extend(labels.cpu().numpy())
        all_predictions.extend(predicted_test.cpu().numpy())

final_test_loss = test_loss / len(test_dataset)
final_test_accuracy = 100 * correct_test / total_test
print(f"\nFinal Test Loss: {final_test_loss:.4f}, Final Test Accuracy: {final_test_accuracy:.2f}%")

# Make class_names available for subsequent cells
class_names = train_dataset.classes

import matplotlib.pyplot as plt
import numpy as np

# Assuming train_losses, train_accuracies, val_losses, val_accuracies, final_test_loss, and final_test_accuracy are available from the previous cell (dbe3612b)

print(f"\nFinal Test Loss: {final_test_loss:.4f}")
print(f"Final Test Accuracy: {final_test_accuracy:.2f}%")

# Plotting Training and Validation Loss
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(range(1, EPOCHS + 1), train_losses, label='Training Loss')
plt.plot(range(1, EPOCHS + 1), val_losses, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss Over Epochs')
plt.legend()
plt.grid(True)

# Plotting Training and Validation Accuracy
plt.subplot(1, 2, 2)
plt.plot(range(1, EPOCHS + 1), train_accuracies, label='Training Accuracy')
plt.plot(range(1, EPOCHS + 1), val_accuracies, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy (%)')
plt.title('Training and Validation Accuracy Over Epochs')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

print(f"Final Test Loss: {final_test_loss:.4f}")
print(f"Final Test Accuracy: {final_test_accuracy:.2f}%")


# Visualize the Confusion Matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix on Test Set')
plt.show()
from sklearn.metrics import classification_report
import numpy as np

# Assuming all_labels and all_predictions are available from the test evaluation loop
# And class_names contains the list of class names in the correct order

# Get the unique labels present in the true labels (all_labels)
unique_labels_in_data = np.unique(all_labels)

# Filter class_names to only include those that are actually present in the data
target_names_for_report = [class_names[label_idx] for label_idx in sorted(unique_labels_in_data)]

print("\nClassification Report:")
print(classification_report(all_labels, all_predictions,
                            labels=sorted(unique_labels_in_data), # Explicitly define the labels to consider
                            target_names=target_names_for_report)) # Use the filtered class names
from sklearn.metrics import confusion_matrix
import numpy as np

# Assuming `cm` (confusion matrix) and `class_names` are available from previous executions

def calculate_specificity(cm):
    specificity_scores = {}
    num_classes = cm.shape[0]

    for i in range(num_classes):
        # True Positives (TP): Diagonal element for class i
        TP = cm[i, i]

        # False Positives (FP): Sum of column i excluding TP
        FP = np.sum(cm[:, i]) - TP

        # False Negatives (FN): Sum of row i excluding TP
        FN = np.sum(cm[i, :]) - TP

        # True Negatives (TN): Sum of all elements excluding row i and column i
        TN = np.sum(cm) - (TP + FP + FN)

        # Specificity = TN / (TN + FP)
        if (TN + FP) == 0:
            specificity = 0.0 # Avoid division by zero, or handle as NaN/None
        else:
            specificity = TN / (TN + FP)
        specificity_scores[class_names[i]] = specificity
    return specificity_scores

specificities = calculate_specificity(cm)

print("\n--- Performance Metrics Summary ---")
print(f"Overall Test Accuracy: {final_test_accuracy:.2f}%")
print("\nSpecificity per class:")
for class_name, spec in specificities.items():
    print(f"  {class_name}: {spec:.2f}")

# Reiterate overall precision, recall, f1-score if available from a previous report
# For this example, we'll re-run a simplified classification report to get averages
# or you can look at the output of the previous classification_report

# Note: Full classification_report output already provided detailed precision, recall, f1-score.
# This part is just to summarize if needed, otherwise refer to the previous output.
