import React, { useState, useEffect } from 'react';
import { io } from 'socket.io-client';
import { motion } from 'motion/react';
import { Play, Image as ImageIcon, CheckCircle, AlertCircle, BarChart2, Eye, RefreshCw, Upload, X, FileText, Database, Sparkles } from 'lucide-react';
import ImageGenerator from './components/ImageGenerator';

interface DatasetItem {
  id: string;
  imageName: string;
  label: string;
  class: string;
  metadata: Record<string, any>;
  previewUrl?: string;
  filePath?: string;
  split?: 'Train' | 'Val' | 'Test';
}

interface TestingPageProps {
  isModelTrained: boolean;
  setIsModelTrained: (val: boolean) => void;
  datasetItems: DatasetItem[];
}

const CLASSES = ["NORMAL", "COVID", "PNEUMONIA", "VIRUS", "BACTERIA"];

export default function TestingPage({ isModelTrained, setIsModelTrained, datasetItems }: TestingPageProps) {
  const [selectedImage, setSelectedImage] = useState<any | null>(null);
  const [isTesting, setIsTesting] = useState(false);
  const [isTraining, setIsTraining] = useState(false);
  const [trainingError, setTrainingError] = useState<string | null>(null);
  const [dataExists, setDataExists] = useState<boolean | null>(null);
  const [testResult, setTestResult] = useState<any | null>(null);

  useEffect(() => {
    fetch('/api/data/check')
      .then(res => res.json())
      .then(data => setDataExists(data.exists))
      .catch(() => setDataExists(false));
  }, []);
  const [isEvaluating, setIsEvaluating] = useState(false);
  const [evaluationMetrics, setEvaluationMetrics] = useState<any | null>(null);
  const [evaluationPlots, setEvaluationPlots] = useState<string[]>([]);
  const [activeTab, setActiveTab] = useState<'dataset' | 'upload' | 'evaluation' | 'generate'>('dataset');
  
  // Upload states
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [uploadPreview, setUploadPreview] = useState<string | null>(null);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [patientInfo, setPatientInfo] = useState({ name: '', age: '', gender: '' });

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0] || null;
    setUploadError(null);
    if (file) {
      if (!file.type.startsWith('image/')) {
        setUploadError('Invalid file type. Please upload an image.');
        return;
      }
      setUploadFile(file);
      const url = URL.createObjectURL(file);
      setUploadPreview(url);
      const newImage = {
        id: `upload-${Date.now()}`,
        imageName: file.name,
        label: 'Unlabeled',
        class: 'Unknown',
        previewUrl: url,
        metadata: { ...patientInfo, source: 'Manual Upload' }
      };
      setSelectedImage(newImage);
    }
  };

  const clearUpload = () => {
    setUploadFile(null);
    setUploadPreview(null);
    setUploadError(null);
    if (selectedImage?.id.startsWith('upload-')) {
      setSelectedImage(null);
    }
  };

  const runTest = async () => {
    if (!selectedImage) return;
    setIsTesting(true);
    setTestResult(null);

    try {
      const response = await fetch('/api/predict', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          imagePath: selectedImage.filePath || selectedImage.previewUrl,
          modelName: 'resnet50' // Default or from settings
        })
      });

      if (!response.ok) throw new Error('Prediction failed');
      
      const result = await response.json();
      
      setTestResult({
        prediction: result.prediction,
        confidence: result.confidence,
        probabilities: result.probabilities,
        metrics: {
          accuracy: 0.92, // Still mock for single image
          precision: 0.89,
          recall: 0.91,
          f1Score: 0.90
        },
        gradCamUrl: selectedImage.previewUrl // Mock heatmap
      });
    } catch (error) {
      console.error('Test error:', error);
    } finally {
      setIsTesting(false);
    }
  };

  const runFullEvaluation = async () => {
    setIsEvaluating(true);
    try {
      const response = await fetch('/api/evaluate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          testDir: '/data/test',
          modelName: 'resnet50'
        })
      });

      if (!response.ok) throw new Error('Evaluation failed');
      
      const metrics = await response.json();
      setEvaluationMetrics(metrics);
      
      // Plots generated by evaluate.py
      setEvaluationPlots([
        '/outputs/confusion_matrix.png',
        '/outputs/confusion_matrix_norm.png',
        '/outputs/roc_curve.png',
        '/outputs/pr_curve.png',
        '/outputs/training_history.png'
      ]);
      
      setActiveTab('evaluation');
    } catch (error) {
      console.error('Evaluation error:', error);
    } finally {
      setIsEvaluating(false);
    }
  };

  const [trainingStatus, setTrainingStatus] = useState<{status: string, progress: number, epoch?: number, totalEpochs?: number} | null>(null);

  useEffect(() => {
    const socket = io();
    socket.on('training:status', (data) => {
      setTrainingStatus(data);
      if (data.status === 'Completed' || data.status === 'Failed') {
        setIsTraining(false);
        if (data.status === 'Completed') setIsModelTrained(true);
      }
    });
    return () => { socket.disconnect(); };
  }, []);

  if (!isModelTrained) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-center p-8">
        <div className="w-20 h-20 bg-red-100 dark:bg-red-900/20 rounded-full flex items-center justify-center mb-6 border-2 border-red-500">
          <AlertCircle className="text-red-500" size={40} />
        </div>
        <h2 className="text-2xl font-bold mb-6 text-[var(--text-color)]">Testing Feature Disabled</h2>
        
        {isTraining && trainingStatus ? (
          <div className="w-full max-w-md space-y-4">
            <div className="w-full bg-gray-200 dark:bg-gray-800 rounded-full h-4 overflow-hidden">
              <motion.div 
                className="bg-[var(--primary-color)] h-full"
                initial={{ width: 0 }}
                animate={{ width: `${trainingStatus.progress}%` }}
              />
            </div>
            <p className="text-sm font-bold text-[var(--text-color)]">
              {trainingStatus.status}: {trainingStatus.progress}% 
              {trainingStatus.epoch && trainingStatus.totalEpochs ? ` (Epoch ${trainingStatus.epoch}/${trainingStatus.totalEpochs})` : ''}
            </p>
          </div>
        ) : (
          <button
            onClick={async () => {
              setIsTraining(true);
              setTrainingStatus(null);
              setTrainingError(null);
              try {
                const response = await fetch('/api/train', { 
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({ epochs: 5 })
                });
                if (!response.ok) {
                  const errorData = await response.json();
                  throw new Error(errorData.error || 'Failed to start training');
                }
              } catch (e: any) {
                console.error('Training failed:', e.message);
                setTrainingError(e.message);
                setIsTraining(false);
              }
            }}
            disabled={isTraining || dataExists === false}
            className="px-6 py-3 bg-[var(--primary-color)] text-[var(--bg-color)] rounded-xl font-bold hover:opacity-90 transition-all disabled:opacity-50 flex items-center gap-2"
          >
            {isTraining ? <RefreshCw className="animate-spin" size={20} /> : <Database size={20} />}
            {isTraining ? 'Starting...' : dataExists === false ? 'Data Missing' : 'Train Model'}
          </button>
        )}
        {trainingError && (
          <div className="mt-4 p-4 bg-red-100 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded-xl border border-red-500/50 text-sm font-bold">
            {trainingError}
          </div>
        )}
        {dataExists === false && (
          <div className="mt-4 p-4 bg-yellow-100 dark:bg-yellow-900/20 text-yellow-600 dark:text-yellow-400 rounded-xl border border-yellow-500/50 text-sm font-bold">
            Data directory not found. Please run the data acquisition pipeline first.
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <header className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-[var(--text-color)]">Local Testing Module</h1>
          <div className="flex items-center gap-2 mt-1">
            <span className="px-2 py-0.5 bg-blue-500 text-white text-[10px] font-bold rounded uppercase tracking-wider">Local Dataset Testing Mode</span>
            <span className="px-2 py-0.5 bg-red-500/10 text-red-500 text-[10px] font-bold rounded border border-red-500/20 uppercase tracking-wider">Gemini API Disabled</span>
          </div>
          <p className="text-[var(--secondary-text)] mt-2">Test the trained model using dataset images (Offline Mode)</p>
        </div>
        <div className="flex items-center gap-2 px-4 py-2 bg-green-500/10 border border-green-500/50 rounded-full text-green-500 text-sm font-bold">
          <CheckCircle size={16} />
          Model Ready
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Sidebar Selection */}
        <div className="lg:col-span-1 space-y-6">
          <div className="flex p-1 bg-[var(--bg-color)] rounded-xl border border-[var(--primary-color)]/20">
            <button
              onClick={() => setActiveTab('dataset')}
              className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-bold transition-all ${
                activeTab === 'dataset'
                  ? 'bg-[var(--primary-color)] text-[var(--bg-color)] shadow-md'
                  : 'text-[var(--secondary-text)] hover:bg-[var(--primary-color)]/10'
              }`}
            >
              <Database size={16} /> Dataset
            </button>
            <button
              onClick={() => setActiveTab('upload')}
              className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-bold transition-all ${
                activeTab === 'upload'
                  ? 'bg-[var(--primary-color)] text-[var(--bg-color)] shadow-md'
                  : 'text-[var(--secondary-text)] hover:bg-[var(--primary-color)]/10'
              }`}
            >
              <Upload size={16} /> Upload
            </button>
            <button
              onClick={() => setActiveTab('evaluation')}
              className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-bold transition-all ${
                activeTab === 'evaluation'
                  ? 'bg-[var(--primary-color)] text-[var(--bg-color)] shadow-md'
                  : 'text-[var(--secondary-text)] hover:bg-[var(--primary-color)]/10'
              }`}
            >
              <BarChart2 size={16} /> Evaluation
            </button>
            <button
              onClick={() => setActiveTab('generate')}
              className={`flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-bold transition-all ${
                activeTab === 'generate'
                  ? 'bg-[var(--primary-color)] text-[var(--bg-color)] shadow-md'
                  : 'text-[var(--secondary-text)] hover:bg-[var(--primary-color)]/10'
              }`}
            >
              <Sparkles size={16} /> Generate
            </button>
          </div>

          {activeTab === 'dataset' ? (
            <div className="space-y-4">
              <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--secondary-text)] flex items-center gap-2">
                <ImageIcon size={16} className="text-[var(--primary-color)]" />
                Select Dataset Image
              </h3>
              <div className="grid grid-cols-1 gap-3 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                {datasetItems.length === 0 ? (
                  <div className="p-8 text-center border-2 border-dashed border-[var(--primary-color)]/20 rounded-xl">
                    <p className="text-sm text-[var(--secondary-text)]">No images in dataset. Please import data first.</p>
                  </div>
                ) : (
                  datasetItems.map((img) => (
                    <button
                      key={img.id}
                      onClick={() => setSelectedImage(img)}
                      className={`p-3 rounded-xl border-2 transition-all text-left flex items-center gap-4 ${
                        selectedImage?.id === img.id
                          ? 'border-[var(--primary-color)] bg-[var(--primary-color)]/10'
                          : 'border-[var(--primary-color)]/20 hover:border-[var(--primary-color)]/50'
                      }`}
                    >
                      {img.previewUrl ? (
                        <img src={img.previewUrl} alt={img.imageName} className="w-12 h-12 rounded-lg object-cover border border-[var(--primary-color)]/30" />
                      ) : (
                        <div className="w-12 h-12 rounded-lg bg-gray-200 dark:bg-gray-800 flex items-center justify-center">
                          <ImageIcon size={20} className="text-gray-400" />
                        </div>
                      )}
                      <div className="overflow-hidden">
                        <p className="text-sm font-bold truncate">{img.imageName}</p>
                        <p className="text-[10px] text-[var(--secondary-text)]">Label: {img.label}</p>
                      </div>
                    </button>
                  ))
                )}
              </div>
            </div>
          ) : activeTab === 'upload' ? (
            <div className="space-y-6">
              <div className="space-y-4">
                <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--secondary-text)] flex items-center gap-2">
                  <FileText size={16} className="text-[var(--primary-color)]" />
                  Patient Information
                </h3>
                <div className="space-y-3">
                  <input 
                    type="text" 
                    placeholder="Patient Name" 
                    value={patientInfo.name}
                    onChange={(e) => setPatientInfo(prev => ({ ...prev, name: e.target.value }))}
                    className="w-full p-3 rounded-xl bg-[var(--bg-color)] border border-[var(--primary-color)]/20 focus:border-[var(--primary-color)] outline-none transition-all text-sm" 
                  />
                  <div className="grid grid-cols-2 gap-3">
                    <input 
                      type="number" 
                      placeholder="Age" 
                      value={patientInfo.age}
                      onChange={(e) => setPatientInfo(prev => ({ ...prev, age: e.target.value }))}
                      className="w-full p-3 rounded-xl bg-[var(--bg-color)] border border-[var(--primary-color)]/20 focus:border-[var(--primary-color)] outline-none transition-all text-sm" 
                    />
                    <select 
                      value={patientInfo.gender}
                      onChange={(e) => setPatientInfo(prev => ({ ...prev, gender: e.target.value }))}
                      className="w-full p-3 rounded-xl bg-[var(--bg-color)] border border-[var(--primary-color)]/20 focus:border-[var(--primary-color)] outline-none transition-all text-sm"
                    >
                      <option value="">Gender</option>
                      <option value="Male">Male</option>
                      <option value="Female">Female</option>
                    </select>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <h3 className="text-sm font-bold uppercase tracking-widest text-[var(--secondary-text)] flex items-center gap-2">
                  <Upload size={16} className="text-[var(--primary-color)]" />
                  Upload X-ray
                </h3>
                <div className="border-2 border-dashed border-[var(--primary-color)]/30 rounded-2xl p-6 text-center">
                  {uploadError && (
                    <p className="text-red-500 text-xs mb-4 font-bold">{uploadError}</p>
                  )}
                  {!uploadPreview ? (
                    <>
                      <input type="file" id="test-upload" className="hidden" onChange={handleFileUpload} accept="image/*" />
                      <label htmlFor="test-upload" className="cursor-pointer flex flex-col items-center gap-2 text-[var(--secondary-text)] hover:text-[var(--primary-color)] transition-colors">
                        <div className="p-4 bg-[var(--primary-color)]/10 rounded-full">
                          <Upload size={32} />
                        </div>
                        <span className="text-xs font-bold">Click to upload scan</span>
                      </label>
                    </>
                  ) : (
                    <div className="space-y-4">
                      <div className="relative inline-block">
                        <img src={uploadPreview} alt="Preview" className="w-32 h-32 rounded-xl object-cover border-2 border-[var(--primary-color)] shadow-lg" />
                        <button 
                          onClick={clearUpload}
                          className="absolute -top-2 -right-2 p-1 bg-red-500 text-white rounded-full shadow-md hover:bg-red-600 transition-colors"
                        >
                          <X size={14} />
                        </button>
                      </div>
                      <p className="text-xs font-bold truncate max-w-[200px] mx-auto">{uploadFile?.name}</p>
                    </div>
                  )}
                </div>
              </div>
            </div>
          ) : activeTab === 'generate' ? (
            <ImageGenerator />
          ) : (
            <div className="space-y-6">
              <div className="p-6 bg-blue-500/5 border-2 border-blue-500/20 rounded-2xl">
                <div className="flex gap-3 items-start">
                  <BarChart2 className="text-blue-500 shrink-0" size={20} />
                  <div className="text-xs">
                    <p className="font-bold text-blue-500 mb-1 uppercase tracking-wider">Full Dataset Evaluation</p>
                    <p className="text-[var(--secondary-text)] leading-relaxed mb-4">
                      Run a comprehensive evaluation on the entire test split to generate advanced metrics and confusion matrices.
                    </p>
                    <button 
                      onClick={runFullEvaluation}
                      disabled={isEvaluating}
                      className="w-full py-3 bg-blue-500 text-white rounded-xl font-bold hover:bg-blue-600 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                    >
                      {isEvaluating ? <RefreshCw className="animate-spin" size={16} /> : <Play size={16} />}
                      {isEvaluating ? 'Evaluating...' : 'Start Evaluation'}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          <button
            onClick={runTest}
            disabled={!selectedImage || isTesting || activeTab === 'generate'}
            className="w-full py-4 bg-[var(--primary-color)] text-[var(--bg-color)] rounded-xl font-bold flex items-center justify-center gap-2 hover:opacity-90 transition-all disabled:opacity-50 shadow-lg shadow-[var(--primary-color)]/20"
          >
            {isTesting ? <RefreshCw className="animate-spin" size={20} /> : <Play size={20} />}
            {isTesting ? 'Processing...' : 'Run Local Test'}
          </button>
        </div>

        {/* Test Results */}
        <div className="lg:col-span-2 space-y-6">
          {!selectedImage && !testResult && (
            <div className="h-full min-h-[400px] border-2 border-dashed border-[var(--primary-color)]/30 rounded-2xl flex flex-col items-center justify-center text-[var(--secondary-text)] p-8">
              <Upload size={48} className="mb-4 text-[var(--primary-color)]" />
              <h3 className="text-xl font-bold text-[var(--text-color)] mb-2">Upload X-ray Scan</h3>
              <p className="text-sm mb-6 text-center max-w-sm">Upload a new X-ray image to test the model directly. Or select an image from the dataset in the sidebar.</p>
              
              {uploadError && (
                <p className="text-red-500 text-xs mb-4 font-bold">{uploadError}</p>
              )}
              <input type="file" id="main-test-upload" className="hidden" onChange={handleFileUpload} accept="image/*" />
              <label htmlFor="main-test-upload" className="px-6 py-3 bg-[var(--primary-color)] text-[var(--bg-color)] rounded-xl font-bold cursor-pointer hover:opacity-90 transition-all shadow-lg shadow-[var(--primary-color)]/20">
                Browse Files
              </label>
            </div>
          )}

          {selectedImage && !testResult && !isTesting && (
            <div className="bg-[var(--bg-color)] rounded-2xl border-2 border-[var(--primary-color)]/30 p-8 flex flex-col items-center justify-center">
              {selectedImage.previewUrl ? (
                <img src={selectedImage.previewUrl} alt="Selected" className="max-w-xs rounded-xl border-2 border-[var(--primary-color)] mb-6 shadow-xl" />
              ) : (
                <div className="w-48 h-48 bg-gray-200 dark:bg-gray-800 rounded-xl flex items-center justify-center mb-6">
                  <ImageIcon size={48} className="text-gray-400" />
                </div>
              )}
              <p className="text-lg font-bold mb-2">{selectedImage.imageName}</p>
              <button
                onClick={runTest}
                disabled={isTesting}
                className="px-6 py-3 bg-[var(--primary-color)] text-[var(--bg-color)] rounded-xl font-bold flex items-center justify-center gap-2 hover:opacity-90 transition-all shadow-lg shadow-[var(--primary-color)]/20"
              >
                {isTesting ? <RefreshCw className="animate-spin" size={20} /> : <Play size={20} />}
                {isTesting ? 'Processing...' : 'Run Local Test'}
              </button>
            </div>
          )}

          {isTesting && (
            <div className="h-full min-h-[400px] flex flex-col items-center justify-center space-y-6">
              <div className="relative">
                <div className="w-24 h-24 border-4 border-[var(--primary-color)]/20 border-t-[var(--primary-color)] rounded-full animate-spin"></div>
                <Activity className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-[var(--primary-color)]" size={32} />
              </div>
              <div className="text-center">
                <p className="text-xl font-bold animate-pulse">Model Inference in Progress</p>
                <p className="text-[var(--secondary-text)]">Processing locally on device...</p>
              </div>
            </div>
          )}

          {testResult && activeTab !== 'evaluation' && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-6"
            >
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Visualizations */}
                <div className="space-y-4">
                  <h4 className="font-bold flex items-center gap-2">
                    <Eye size={18} className="text-[var(--primary-color)]" />
                    Grad-CAM Visualization
                  </h4>
                  <div className="relative group rounded-xl overflow-hidden border-2 border-[var(--primary-color)] shadow-xl">
                    {selectedImage?.previewUrl ? (
                      <img src={selectedImage.previewUrl} alt="Original" className="w-full h-auto" />
                    ) : (
                      <div className="aspect-square bg-gray-200 dark:bg-gray-800 flex items-center justify-center">
                        <ImageIcon size={48} className="text-gray-400" />
                      </div>
                    )}
                    <div className="absolute inset-0 bg-gradient-to-tr from-red-500/40 via-yellow-500/20 to-transparent mix-blend-overlay"></div>
                    <div className="absolute bottom-4 left-4 bg-black/60 backdrop-blur-md px-3 py-1 rounded-full text-xs text-white font-bold border border-white/20">
                      Heatmap Overlay Active
                    </div>
                  </div>
                </div>

                {/* Prediction Details */}
                <div className="space-y-6">
                  <div className="p-6 bg-[var(--primary-color)]/10 rounded-2xl border-2 border-[var(--primary-color)]">
                    <p className="text-sm text-[var(--secondary-text)] uppercase tracking-wider mb-1">Predicted Class</p>
                    <h2 className="text-4xl font-black text-[var(--primary-color)] mb-4">{testResult.prediction}</h2>
                    
                    <p className="text-sm text-[var(--secondary-text)] uppercase tracking-wider mb-1">Confidence Score</p>
                    <div className="flex items-center gap-4">
                      <div className="flex-1 h-3 bg-[var(--primary-color)]/20 rounded-full overflow-hidden">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${testResult.confidence * 100}%` }}
                          className="h-full bg-[var(--primary-color)]"
                        />
                      </div>
                      <span className="text-xl font-bold">{(testResult.confidence * 100).toFixed(1)}%</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="p-4 bg-[var(--bg-color)] rounded-xl border border-[var(--primary-color)]/30">
                      <p className="text-xs text-[var(--secondary-text)] uppercase mb-1">Accuracy</p>
                      <p className="text-xl font-bold">{(testResult.metrics.accuracy * 100).toFixed(1)}%</p>
                    </div>
                    <div className="p-4 bg-[var(--bg-color)] rounded-xl border border-[var(--primary-color)]/30">
                      <p className="text-xs text-[var(--secondary-text)] uppercase mb-1">F1 Score</p>
                      <p className="text-xl font-bold">{testResult.metrics.f1Score.toFixed(2)}</p>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {activeTab === 'evaluation' && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-8"
            >
              {evaluationMetrics ? (
                <div className="space-y-8">
                  {/* Summary Metrics */}
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div className="p-6 bg-[var(--bg-color)] rounded-2xl border-2 border-[var(--primary-color)]/20 text-center">
                      <p className="text-xs font-bold text-[var(--secondary-text)] uppercase mb-2">Accuracy</p>
                      <p className="text-3xl font-black text-[var(--primary-color)]">{(evaluationMetrics.overall.accuracy * 100).toFixed(1)}%</p>
                    </div>
                    <div className="p-6 bg-[var(--bg-color)] rounded-2xl border-2 border-[var(--primary-color)]/20 text-center">
                      <p className="text-xs font-bold text-[var(--secondary-text)] uppercase mb-2">F1 Score</p>
                      <p className="text-3xl font-black text-[var(--primary-color)]">{evaluationMetrics.overall.f1_weighted.toFixed(3)}</p>
                    </div>
                    <div className="p-6 bg-[var(--bg-color)] rounded-2xl border-2 border-[var(--primary-color)]/20 text-center">
                      <p className="text-xs font-bold text-[var(--secondary-text)] uppercase mb-2">ROC-AUC</p>
                      <p className="text-3xl font-black text-[var(--primary-color)]">{evaluationMetrics.overall.roc_auc_ovr.toFixed(3)}</p>
                    </div>
                    <div className="p-6 bg-[var(--bg-color)] rounded-2xl border-2 border-[var(--primary-color)]/20 text-center">
                      <p className="text-xs font-bold text-[var(--secondary-text)] uppercase mb-2">PR-AUC</p>
                      <p className="text-3xl font-black text-[var(--primary-color)]">{evaluationMetrics.overall.pr_auc.toFixed(3)}</p>
                    </div>
                  </div>

                  {/* Plots Grid */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    {evaluationPlots.map((plot, idx) => (
                      <div key={idx} className="space-y-4">
                        <h5 className="text-sm font-bold uppercase tracking-widest text-[var(--secondary-text)]">
                          {plot.split('/').pop()?.replace('.png', '').replace(/_/g, ' ')}
                        </h5>
                        <div className="rounded-2xl overflow-hidden border-2 border-[var(--primary-color)]/20 bg-white p-2">
                          <img src={plot} alt="Plot" className="w-full h-auto" />
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ) : (
                <div className="h-full min-h-[400px] flex flex-col items-center justify-center text-[var(--secondary-text)] opacity-50">
                  <BarChart2 size={64} className="mb-4" />
                  <p className="font-bold uppercase tracking-widest">No Evaluation Data</p>
                  <p className="text-sm">Run a full evaluation to see detailed metrics and plots.</p>
                </div>
              )}
            </motion.div>
          )}
        </div>
      </div>
    </div>
  );
}

const Activity = ({ className, size }: { className?: string, size?: number }) => (
  <svg 
    xmlns="http://www.w3.org/2000/svg" 
    width={size} 
    height={size} 
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="2" 
    strokeLinecap="round" 
    strokeLinejoin="round" 
    className={className}
  >
    <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
  </svg>
);
